{% set unix_version = "5.38.2" %}
{% set win_version = unix_version + ".2" %}

package:
  name: perl
  version: {{ unix_version }}  # [not win]
  version: {{ win_version }}   # [win]

source:
  - url: http://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.xz                                                 # [unix]
    sha256: d91115e90b896520e83d4de6b52f8254ef2b70a8d545ffab33200ea9f1cf29e8                                        # [unix]
  - url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-64bit-portable.zip  # [win]
    sha256: ea451686065d6338d7e4d4a04c9af49f17951d15aa4c2e19ab8cb56fa2373440                                        # [win]
    # sha hashes published at: http://strawberryperl.com/releases.html

build:
  number: 0

requirements:
  build:
    - make                  # [unix]
  host:
    - {{ compiler('c') }}   # [unix]
    - binutils              # [linux]
    - gdbm                  # [unix]
  run:
    - gdbm >=1.18           # [unix]
    # If something needs to be compiled using Perl's C support,
    # you need to make sure the compiler is in same PREFIX as the perl
    # interpreter.
    # Additional be aware the the used sysroot is hard-coded in perl's
    # configuration at many places.  So on osx it means that SDK will be
    # searched at intially used place.  CONDA_BUILD_PREFIX is disregarded.
test:
  commands:
    - perl --help

about:
  home: https://www.perl.org/
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - Artistic  # [unix]
    - Copying   # [unix]
    - licenses/perl/Artistic  # [win]
    - licenses/perl/Copying  # [win]
  license_url: https://dev.perl.org/licenses/  # [unix]
  license_url: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/master/LICENSE # [win]
  summary: "The Perl programming language interpreter."
  license_family: Other
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
    - katietz
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
    - missing_license_file
