{% set unix_version = "5.34.0" %}

package:
  name: perl
  version: {{ unix_version }}

source:
  url: https://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.gz                                                 # [unix]
  sha256: 551efc818b968b05216024fb0b727ef2ad4c100f8cb6b43fab615fa78ae5be9a                                        # [unix]
build:
  number: 1
  # there is no Windows strawberry release of this version
  skip: True  # [win]
requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - binutils              # [linux]
    - make                  # [unix]
    - gdbm                  # [unix]
test:
  commands:
    - perl --help

about:
  home: https://www.perl.org/
  license: Perl Artistic
  license_family: Other
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
    - katietz
