{% set unix_version = "5.32.0" %}
{% set win_version = unix_version + ".1" %}

package:
  name: perl
  version: {{ unix_version }}  # [not win]
  version: {{ win_version }}   # [win]

source:
  url: http://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.gz                                                 # [unix]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-64bit-portable.zip  # [win64]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-32bit-portable.zip  # [win32]
  sha256: efeb1ce1f10824190ad1cadbcccf6fdb8a5d37007d0100d2d9ae5f2b5900c0b4                                        # [unix]
  # sha1 hashes published at: http://strawberryperl.com/releases.html
  sha1: 9ec5ebc865da82eacc2d95ff2976492ca69934ab                                                                  # [win64]
  sha1: 6ad89c6358a174c048f113bfd274d2d0378d60aa                                                                  # [win32]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - make                  # [unix]

test:
  # downstreams:
  #   - git
  #   - automake
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic-1.0-Perl
  license_file:
    - Artistic  # [unix]
    - Copying   # [unix]
    - licenses/perl/Artistic  # [win]
    - licenses/perl/Copying  # [win]
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
