{% set unix_version = "5.30.3" %}
{% set win_version = unix_version + ".1" %}

package:
  name: perl
  version: {{ unix_version }}  # [not win]
  version: {{ win_version }}   # [win]

source:
  url: http://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.gz                                                 # [unix]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-64bit-portable.zip  # [win64]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-32bit-portable.zip  # [win32]
  sha256: 32e04c8bb7b1aecb2742a7f7ac0eabac100f38247352a73ad7fa104e39e7406f                                        # [unix]
  # sha1 hashes published at: http://strawberryperl.com/releases.html
  sha1: 487a15ab60bdc41ed72626b6b4fb260d755d4a98                                                                  # [win64]
  sha1: c4211d4651620506412f757ea221ee6088f2ed91                                                                  # [win32]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - make                  # [unix]

test:
  # downstreams:
  #   - git
  #   - automake
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic-1.0-Perl
  license_file:
    - Artistic  # [unix]
    - Copying   # [unix]
    - licenses/perl/Artistic  # [win]
    - licenses/perl/Copying  # [win]
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
