{% set base_version = "5.22.0" %}
{% set version = base_version + ".1" %}


package:
  name: perl
  version: {{ version }}

source:
  fn: perl-{{ base_version }}.tar.gz                                                                       # [unix]
  fn:  strawberry-perl-{{ version }}-32bit-portable.zip                                                    # [win]
  url: http://www.cpan.org/src/5.0/perl-{{ base_version }}.tar.gz                                          # [unix]
  url:  http://strawberryperl.com/download/{{ version }}/strawberry-perl-{{ version }}-32bit-portable.zip  # [win]
  sha1: 400338c91c56420d98142cbfcb84d418cae2c98c                                                           # [unix]
  sha1: ffc41fe8ebc03802ea59f4b88aa34a154af4d55d                                                        # [win]

build:
  number: 0

test:
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Artistic License
  license_family: Other
  license: Perl
  summary: "The Perl programming language interpreter."


extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
